# Generated by Django 2.2.6 on 2019-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('money', models.BigIntegerField()),
                ('has', models.CharField(max_length=1000)),
                ('cart', models.CharField(max_length=1000)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('age', models.BigIntegerField()),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32)),
                ('height', models.BigIntegerField()),
                ('weight', models.BigIntegerField()),
                ('img_url', models.CharField(max_length=200)),
                ('new', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '宠物项',
                'verbose_name_plural': '宠物项',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiveModel',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pluginModelPath', models.CharField(max_length=200)),
                ('model_jsonPath', models.CharField(max_length=200)),
                ('model_scale', models.DecimalField(decimal_places=4, max_digits=5)),
                ('display_position', models.CharField(max_length=20)),
                ('display_width', models.BigIntegerField()),
                ('display_height', models.BigIntegerField()),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'ordering': ['title'],
            },
        ),
    ]
